<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Charm.Renderer</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>AnyCPU;x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <OutputPath>..\Charm\bin\$(Platform)\$(Configuration)\</OutputPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Renderer Assets\Shaders\blit.hlsl" />
    <None Remove="Renderer Assets\Shaders\blit_linear.hlsl" />
    <None Remove="Renderer Assets\Shaders\blit_srgb.hlsl" />
    <None Remove="Renderer Assets\Shaders\clear_ao.hlsl" />
    <None Remove="Renderer Assets\Shaders\debug_lines_ps.hlsl" />
    <None Remove="Renderer Assets\Shaders\debug_lines_vs.hlsl" />
    <None Remove="Renderer Assets\Shaders\entity_vs_override.hlsl" />
    <None Remove="Renderer Assets\Shaders\entity_vs_override_vc.hlsl" />
    <None Remove="Renderer Assets\Shaders\full_hemi_sky_temp_ps.hlsl" />
    <None Remove="Renderer Assets\Shaders\full_hemi_sky_temp_vs.hlsl" />
    <None Remove="Renderer Assets\Shaders\grid.hlsl" />
    <None Remove="Renderer Assets\Shaders\investment_ps_override.hlsl" />
    <None Remove="Renderer Assets\Shaders\investment_vs_override.hlsl" />
    <None Remove="Renderer Assets\Shaders\investment_vs_override_vc.hlsl" />
    <None Remove="Renderer Assets\Shaders\luminance.hlsl" />
    <None Remove="Renderer Assets\Shaders\matcap.hlsl" />
    <None Remove="Renderer Assets\Shaders\screen_area_global_lut3d_no_tonemap_distort.hlsl" />
    <None Remove="Renderer Assets\Shaders\shadow_map.hlsl" />
    <None Remove="Renderer Assets\Textures\matcap.png" />
    <None Remove="Renderer Assets\Textures\matcap_new.png" />
    <None Remove="Renderer Assets\Textures\matcap_specular.png" />
    <None Remove="Renderer Assets\Textures\matcap_specular_new.png" />
    <None Remove="Renderer Assets\Textures\vignette.dds" />
    <None Remove="Renderer Assets\Textures\vignette.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Evergine.Bindings.RenderDoc" Version="2024.10.7.18" />
    <PackageReference Include="TracyWrapper" Version="0.20.2" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Renderer Assets\Shaders\blit.hlsl">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Renderer Assets\Shaders\blit_linear.hlsl">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Renderer Assets\Shaders\clear_ao.hlsl">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Renderer Assets\Shaders\debug_lines_vs.hlsl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Renderer Assets\Shaders\debug_lines_ps.hlsl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Renderer Assets\Shaders\entity_vs_override.hlsl">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Renderer Assets\Shaders\entity_vs_override_vc.hlsl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Renderer Assets\Shaders\full_hemi_sky_temp_ps.hlsl">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Renderer Assets\Shaders\full_hemi_sky_temp_vs.hlsl">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Renderer Assets\Shaders\grid.hlsl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Renderer Assets\Shaders\investment_vs_override.hlsl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Renderer Assets\Shaders\investment_vs_override_vc.hlsl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Renderer Assets\Shaders\matcap.hlsl">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Renderer Assets\Shaders\screen_area_global_lut3d_no_tonemap_distort.hlsl">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Renderer Assets\Shaders\shadow_map.hlsl">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Renderer Assets\Textures\matcap.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Renderer Assets\Textures\matcap_new.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Renderer Assets\Textures\matcap_specular.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Renderer Assets\Textures\matcap_specular_new.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Renderer Assets\Textures\vignette.dds">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Charm.Shared\Charm.Shared.csproj" Private="false" />
    <ProjectReference Include="..\Charm\Charm.csproj" />
    <ProjectReference Include="..\Tiger\Tiger.csproj" Private="false" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="RD /S /Q &quot;$(TargetDir)cs\&quot;&#xD;&#xA;RD /S /Q &quot;$(TargetDir)da\&quot;&#xD;&#xA;RD /S /Q &quot;$(TargetDir)de\&quot;&#xD;&#xA;RD /S /Q &quot;$(TargetDir)es\&quot;&#xD;&#xA;RD /S /Q &quot;$(TargetDir)fa\&quot;&#xD;&#xA;RD /S /Q &quot;$(TargetDir)fi\&quot;&#xD;&#xA;RD /S /Q &quot;$(TargetDir)fr\&quot;&#xD;&#xA;RD /S /Q &quot;$(TargetDir)it\&quot;&#xD;&#xA;RD /S /Q &quot;$(TargetDir)ko\&quot;&#xD;&#xA;RD /S /Q &quot;$(TargetDir)mk\&quot;&#xD;&#xA;RD /S /Q &quot;$(TargetDir)nl\&quot;&#xD;&#xA;RD /S /Q &quot;$(TargetDir)pl\&quot;&#xD;&#xA;RD /S /Q &quot;$(TargetDir)pt\&quot;&#xD;&#xA;RD /S /Q &quot;$(TargetDir)ru\&quot;&#xD;&#xA;RD /S /Q &quot;$(TargetDir)sv\&quot;&#xD;&#xA;RD /S /Q &quot;$(TargetDir)tr\&quot;&#xD;&#xA;RD /S /Q &quot;$(TargetDir)zh-CN\&quot;&#xD;&#xA;RD /S /Q &quot;$(TargetDir)ja\&quot;&#xD;&#xA;RD /S /Q &quot;$(TargetDir)pt-BR\&quot;&#xD;&#xA;RD /S /Q &quot;$(TargetDir)zh-Hans\&quot;&#xD;&#xA;RD /S /Q &quot;$(TargetDir)zh-Hant\&quot;" />
  </Target>

</Project>
